In [2]:
import pandas as pd
import numpy as np
import pickle
import pandas_profiling as pd_prof
from sklearn.preprocessing import scale, MinMaxScaler

%load_ext autoreload
%autoreload 2
from per_user_product_freq_v2   import user_product_freq

pd.options.mode.chained_assignment = 'warn' 

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'last_expr'

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [34]:
# store data files in  variables. all named DA_$file_name
data_files = [#"aisles",
               # "departments",
                #"order_products__prior",
                #"orders",
                "products",
                "sample_submission"
                ]
for file_name in data_files :
    exec( "DA_{0} = pd.read_csv('./data/{0}.csv')".format(file_name) )


In [25]:
with open('./data/pickles/product_freq_df.pkl', 'rb') as f:
    products_freq = pickle.load(f);

In [ ]:
# using pandas profile Report lib. 
#profile = pd_prof.ProfileReport(DA_departments)
#profile.to_file('./departments_profile_report.html')

In [4]:
user_id = 3
orders = DA_orders[DA_orders.user_id == user_id];
products = DA_order_products__prior[DA_order_products__prior.order_id.isin(orders.order_id)];
user_freq = user_product_freq(orders, products)

In [27]:
#norm_user_freq = user_freq.apply(lambda d: d - np.median(d) / d.max(),axis=1)
norm_product_freq = products_freq.apply(lambda d: d - np.median(d) / d.max(),axis=1)

/usr/lib/python2.7/site-packages/ipykernel/__main__.py:2: RuntimeWarning: invalid value encountered in double_scalars
  from ipykernel import kernelapp as app


In [5]:
tmp = np.array([[1, 5, 1000, 2],[0, 0, 2, 0],[3, 3, 3, 3]],dtype=float).transpose()

In [35]:
#products_freq.loc[49683]
DA_products.loc[49683]

product_id                                           49684
product_name     Vodka, Triple Distilled, Twist of Vanilla
aisle_id                                               124
department_id                                            5
Name: 49683, dtype: object

order_id     products
0            17  39276 29259
1            34  39276 29259
2           137  39276 29259
3           182  39276 29259
4           257  39276 29259
5           313  39276 29259
6           353  39276 29259
7           386  39276 29259
8           414  39276 29259
9           418  39276 29259
10          437  39276 29259
11          452  39276 29259
12          474  39276 29259
13          492  39276 29259
14          497  39276 29259
15          513  39276 29259
16          517  39276 29259
17          604  39276 29259
18          680  39276 29259
19          758  39276 29259
20          759  39276 29259
21          887  39276 29259
22         1161  39276 29259
23         1195  39276 29259
24         1304  39276 29259
25         1408  39276 29259
26         1513  39276 29259
27         1564  39276 29259
28         1727  39276 29259
29         1789  39276 29259
...         ...          ...
74970   3419522  39276 29259
74971   3419568  39276 29259
74972   3419574  39276 29259
74973   3419600  39276 29259
74974   3419623  39276 29259
74975   3419726  39276 29259
74976   3419729  39276 29259
74977   3419732  39276 29259
74978   3419743  39276 29259
74979   3419832  39276 29259
74980   3419878  39276 29259
74981   3419910  39276 29259
74982   3419934  39276 29259
74983   3420147  39276 29259
74984   3420168  39276 29259
74985   3420237  39276 29259
74986   3420327  39276 29259
74987   3420360  39276 29259
74988   3420390  39276 29259
74989   3420443  39276 29259
74990   3420449  39276 29259
74991   3420544  39276 29259
74992   3420569  39276 29259
74993   3420651  39276 29259
74994   3420702  39276 29259
74995   3420740  39276 29259
74996   3420877  39276 29259
74997   3420888  39276 29259
74998   3420989  39276 29259
74999   3421054  39276 29259

[75000 rows x 2 columns]

In [ ]:
scaler = MinMaxScaler(feature_range=[0,2])
scaler.fit_transform(tmp[:,2])

In [11]:
p[0][1]

0.0

In [15]:
min_ = 0;
tmp2 = tmp.copy()
for i in range(0,3):
    max_ = tmp[:,i].max()
    mean = np.median(tmp[:,i])
    tmp2[:,i] = (tmp[:,i] - mean ) / max_
tmp2
    

array([[-0.0025,  0.    ,  0.    ],
       [ 0.0015,  0.    ,  0.    ],
       [ 0.9965,  1.    ,  0.    ],
       [-0.0015,  0.    ,  0.    ]])

In [10]:
tm3

array([[-0.251, -0.25 ,  0.   ],
       [-0.247, -0.25 ,  0.   ],
       [ 0.748,  0.75 ,  0.   ],
       [-0.25 , -0.25 ,  0.   ]])

In [13]:
tm4 

array([[ 0.001,  0.   ,  1.   ],
       [ 0.005,  0.   ,  1.   ],
       [ 1.   ,  1.   ,  1.   ],
       [ 0.002,  0.   ,  1.   ]])

In [ ]:
p = user_product_freq(1)

In [ ]:
p = pd.DataFrame(data=np.zeros(shape=[20,168]),index=np.arange(1,21))

In [ ]:
p[104]